### PR TITLE
Update to supported ruby versions

### PR DESCRIPTION
**Pull request by fliiiix**
Can you create a new release with that?

### CODE REVIEW

**Comment by edgar** [comment]
@fliiiix thanks for your PR, I'll merge it, however theses changes don't impact the Gem's behavior, any reason you want a new release?

**Comment by fliiiix** [comment]
Thanks :tada: 

> however theses changes don't impact the Gem's behavior

This is true but, mostly because there was no release after https://github.com/edgar/feedvalidator/commit/0d29292554113b63bb1a5d0d7ed4065d7892a5c0 which does impact our CI system since it produces a warning on each run

**Comment by edgar** [comment]
v0.2.2 released https://rubygems.org/gems/feedvalidator

**Comment by fliiiix** [comment]
Thank you very much :tada: :+1:

**Pull request merged**
